### ISSUE TITLE
npm-run-all hangs on ctrl + c

### ISSUE THREAD

**Issue by corysimmons** [begin-examples/node-create-react-app#93]
Have to hold down `ctrl + c` for a while before it will actually terminate `npm start`

Replacing it with https://npm.im/concurrently terminates correctly, but ends up throwing `TypeError: process.stdin.setRawMode is not a function` and `Proxy error: Could not proxy request /api from localhost:3000 to http://localhost:3333`

**Comment by kristoferjoseph** [comment]
Fixed by latest sandbox update.
